name: Test Automation

on:
  push:
    branches:
      - master

jobs:
  pytest-python39:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest --browser ${{ matrix.browser }}
